### ISSUE TITLE
Tracking points between key frames?

### ISSUE THREAD

**Issue by jhofman** [microsoft/datamations#106]
The issue of tracking data points across key frames came up today.

Right now we don't handle this, but at some point we might want to (e.g., if we filter data or something like that).

Not urgent, but just creating this so that we don't lose it as something to think about.

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand can you make some test specs for this?

**Comment by jhofman** [comment]
sounds like we need manual visual inspection of renderings w/ the R-generated point ids instead of automatic tests of json specs.

@sharlagelfand will use a local version of the shiny app on the as of now unmerged branch to visually check this.

one grouping is worked out and visual checks are good we can merge.

**Comment by sharlagelfand** [comment]
Can confirm on the visual checks, the R generated IDs look good and the same as when the IDs are generated on the JS side! 🎉

**Comment by sharlagelfand** [comment]
Will close when #118 is merged
