### ISSUE TITLE
Two-variable grouping in Python

### ISSUE THREAD

**Issue by jhofman** [microsoft/datamations#121]
Python handles one-variable grouping at the moment.

Let's extend that to two variables and then write a test case for it, as in the second example in the main README.

@sharlagelfand, can you show @chisingh how to get the specs out of that example?

**Comment by sharlagelfand** [comment]
Here's how you can get the specs:

```r
example_specs <- "small_salary %>%
  group_by(Degree, Work) %>% 
  summarize(mean = mean(Salary))" %>%
  datamation_sanddance()

example_specs$x$specs
```
