### ISSUE TITLE
Abstract away column names in frame generation functions

### ISSUE THREAD

**Issue by jhofman** [microsoft/datamations#14]
Right now the specific "salary" and "degree" column names are used inside of the frame generation functions in d3. If we end up going with our own d3 code for generating frames we'll need to abstract this away to "x" and "y" and have some way to pass which column names map to which variables when calling r2d3.

Let's put this on hold until we figure out #12.

**Comment by jhofman** [comment]
@giorgi-ghviniashvili seems like this will be solved if we go with vegalite + gemini.

assuming so, let's close this out?

**Comment by sharlagelfand** [comment]
Definitely solved!
