### ISSUE TITLE
fix x label jitter between group-by grid and next frame for unequal sized groups

### ISSUE THREAD

**Issue by jhofman** [microsoft/datamations#143]
sometimes when we have uneven sized groups and we go from infogrid to scatter plot, we see the x axis label jitter a bit. here's an example from 7 seconds to 10 seconds:

https://github.com/microsoft/datamations/issues/62#issuecomment-1063869253

let's try some alternatives for giving each group equal amounts of the x axis so that it lines up with the next frame.

**Comment by jhofman** [comment]
okay @giorgi-ghviniashvili, i think this is step in the right direction so let's see how it goes with bigger groups.

also, a note to update the fake data you're using there to have the correct number of points for phd in the first frame. (right now it's a copy of the masters data, mistakenly).

**Comment by giorgi-ghviniashvili** [comment]
@jhofman no jump at all:

https://user-images.githubusercontent.com/6615532/159290996-e140588a-7619-4464-ade3-8fc99d0defaf.mov

**Comment by jhofman** [comment]
closes #148
