### ISSUE TITLE
Clean up final error bars on zoom

### ISSUE THREAD

**Issue by jhofman** [microsoft/datamations#161]
@giorgi-ghviniashvili: can we clean up the final error bar zooming from seconds 16 to 18 in this recording?

https://user-images.githubusercontent.com/79563/161065544-d9525ab5-59af-46ab-9c34-a34b62038d6c.mov

would it be possible to just have the existing error bars and points zoom in instead of removing and redrawing them? they also show up slightly misaligned (off to the right)

**Comment by giorgi-ghviniashvili** [comment]
@jhofman I could not specify min-width for the axis. It translates the whole chart to the right anyway when axis labels have decimals. 

Instead I fixed the error bars like this: it waits the points to be transformed and then the error bars appear. Will that work?

https://user-images.githubusercontent.com/6615532/161259702-9020d2ad-1915-4b92-9d6a-162fb2b0d0aa.mov
