### ISSUE TITLE
Penguins example breaks with 2 or 3 variables in shiny app

### ISSUE THREAD

**Issue by jhofman** [microsoft/datamations#165]
No datamation is shown when grouping on more than just species

```
library(palmerpenguins)
library(dplyr)
penguins %>%
  group_by(species, island, sex) %>%
  summarize(mean = mean(bill_length_mm, na.rm = TRUE))
```
![Screen Shot 2022-03-31 at 10 35 22 AM](https://user-images.githubusercontent.com/79563/161080900-e1ff3d4b-4c37-4363-a66b-38a0d486ef26.png)

**Comment by willdebras** [comment]
I cannot reproduce issues here with the penguins specifically, but I do believe something odd is happening with this modules based app called from `datamations::run_app()`. It seems sometimes when a datamation has been rendered, re-pressing `Go` will not render a new datamation. This might be related to what you are running into. This seems to not be a problem with the demo application at all, so we can consider just switch what datamations::run_app() references to the demo-app.

**Comment by jhofman** [comment]
Seems okay with me, #166 takes care of penguins working!
