### ISSUE TITLE
Find a spot for the updated shiny app

### ISSUE THREAD

**Issue by jhofman** [microsoft/datamations#166]
Perhaps a sub-folder?

Also let's add @willdebras's tips on how to debug shiny apps for our future selves

**Comment by willdebras** [comment]
https://github.com/microsoft/datamations/tree/main/demo-app

New demo application with binary examples + custom animations (e.g. quantile) is housed here:

https://github.com/microsoft/datamations/tree/main/demo-app

I added `^demo-app$` to `.Rbuildignore` so it gets excluded in the build.

I also added the in progress work for adding filter and mutation steps to a new branch:

https://github.com/microsoft/datamations/commit/9c3e9ca7bf6a2c934a44637edf94ba56fe91ce37
