### ISSUE TITLE
Identify integration points for d3.js in current code

### ISSUE THREAD

**Issue by jhofman** [microsoft/datamations#3]
Right now the code uses [ggplot2](https://ggplot2.tidyverse.org), [gganimate](https://gganimate.com), and its lower-level cousin [tweenr](https://github.com/thomasp85/tweenr) to render animations.

We'll need to figure out the right place to hand off rendering to d3.js. We can do this narrowly, but we want to strike a good balance of ease of use and modularity with flexibility.

**Comment by jhofman** [comment]
We discussed this a bit further today on our call with @giorgi-ghviniashvili. Adding a few notes.

Imagine someone writes something like this in R and wants to "datamate" it:

```
salary_data %>%
  group_by(degree) %>%
  summarize(mean_salary = mean(salary),
            se = ... ) %>%
  ggplot(aes(x = degree, y = mean_salary, color = degree)) +
  geom_pointrange( ... )
```

In order to datamate this, we can break things down into three high-level steps.

1. The first step to datamating is to translate each line in the code into some type of visual state *conceptually*. Let's call these "key states". For instance, we decided that line 1 above should be represented as an icon array (an array of uncolored points, one for each data point). Line 2 should split this array into two groups, colored by degree. And so on. We can think of this as follows: "line 1 -> uncolored icon array", "line 2 -> colored icon array", etc.
2. The second step to datamating is to take each of these key states and actually render them into some coordinate system that can be displayed on a screen. This goes beyond the conceptual step in 1 by actually assigning, say, x and y coordinates and a color for each point, so something like "line1 -> uncolored icon array -> [(point 1, x = 1, y = 1, color = grey), (point 2, x = 2, y = 1), ...]".
3. The third step is to create transitions between the rendered key frames from the previous step, resulting in the full datamation.

In order to have the final datamation render in d3, as I see it we have two options: hand off the output of step 1 to d3 or hand off the output of step 2 to d3. The first (Option A) puts a lot more work on the d3 side and means that we might need an entire plotting grammar in d3, which seems daunting, but it makes it easy to adapt to lots of different base languages (Python instead of R, for instance). The second (Option B) requires that the base language does much more work, and hands d3 coordinates. This seems quite flexible, but puts the burden on the the base language side.

Right now I'd lean towards Option B, but just getting this down here for discussion.

Things that could be useful:

  * [Vega](https://vega.github.io/vega/examples/error-bars/), a grammar for d3
  * [Plotly for R](https://plotly.com/r/)

**Comment by giorgi-ghviniashvili** [comment]
I got the point. 

If we lean towards Option B and make d3 completely unaware of coordinate calculations, then we will loose the chart responsiveness for different width and height, but if that's not a big deal and charts will just be static size always, Option B will work. 

Vega is really a great library, I will play with it and see how it works. 

Seems like that coordinate calculation should either be in base language or d3 side, but what about writing a completely separate middleware module that will only do that. In that way, we will be able to have any base language or any visualization language. 

As a starting point I am doing coordinate calculation in the chart script, but can easily refactor it to another file / repository.

**Comment by sharlagelfand** [comment]
I'd call this closed :)
