### ISSUE TITLE
Link to js dependencies instead of storing locally

### ISSUE THREAD

**Issue by sharlagelfand** [microsoft/datamations#41]
Need to figure out a way to link out to the dependencies instead of [having them locally](https://github.com/jhofman/datamations/tree/refactor-test/inst/htmlwidgets) - there is [an issue](https://github.com/ramnathv/htmlwidgets/issues/79) indicating this _wasn't_ possible at some point, but I'll keep digging to see if it is now or if we can find some other creative solution.

**Comment by sharlagelfand** [comment]
It seems that all the libraries we're using allow for redistribution in code as long as the copyright notice is also retained, they all use the BSD 3-Clause License:

* [D3](https://github.com/d3/d3/blob/master/LICENSE)
* [vega](https://github.com/vega/vega/blob/master/LICENSE)
* [vega-lite](https://github.com/vega/vega-lite/blob/master/LICENSE)
* [vega-embed](https://github.com/vega/vega-embed/blob/master/LICENSE)
* [gemini](https://github.com/uwdata/gemini/blob/master/LICENSE)

Seems like how this is done in other libraries (e.g. plotly) is by [including the license](https://github.com/ropensci/plotly/tree/master/inst/htmlwidgets/lib/plotlyjs) in the directory where the code is.

Something to keep in mind in case I can't figure out linking to them - might also be useful because linking out inherently means that the widgets can only be used online.

cc @jhofman

**Comment by jhofman** [comment]
@sharlagelfand sounds good on including the licenses in the library subdirs. thanks!
