### ISSUE TITLE
Add data point information on hover?

### ISSUE THREAD

**Issue by jhofman** [microsoft/datamations#46]
@giorgi-ghviniashvili is it possible to add tooltip hover over to the points on plots in vegalite / gemini?

if so this could be really useful, both for debugging (for instance to know what the summarized values are in the final frame when checking if the axes are right) and for causal users who want to see more about that datapoint.

**Comment by giorgi-ghviniashvili** [comment]
@jhofman we had weird issues on hover with gemini, but will try to make it work. Vega supports [tooltips](https://vega.github.io/vega-lite/docs/tooltip.html).

**Comment by giorgi-ghviniashvili** [comment]
@jhofman I set `tooltip: true` to the spec, it works in vega, but has issues in gemini, maybe better to ask gemini guys about this error?

![image](https://user-images.githubusercontent.com/6615532/118012110-c6984680-b361-11eb-9436-27d782858f04.png)


![image](https://user-images.githubusercontent.com/6615532/118012079-bed8a200-b361-11eb-8558-9a47e1e0909c.png)

**Comment by jhofman** [comment]
got it.

can you create an issue on the gemini project?

thanks!

**Comment by giorgi-ghviniashvili** [comment]
https://github.com/uwdata/gemini/issues/7

**Comment by jhofman** [comment]
This will require work on #49 for a solution that works during animations. But until then let's see if there's a way to hack this just for static frames (and not the full animation) with vegalite.

The imagined use case is that someone's in the shiny app, then select a key frame, and want to see more about a particular point so they hover over it.

**Comment by giorgi-ghviniashvili** [comment]
@jhofman , tooltip works well , we just need to set `mark.tooltip = true`. It will just display tooltip correctly:

![image](https://user-images.githubusercontent.com/6615532/125982544-468e6945-a5ca-4568-b055-90302da078d5.png)

The problem is that after gemini animation, it starts printing this error: 
 
![image](https://user-images.githubusercontent.com/6615532/125982673-cedb8f76-9334-4762-8467-4648636ef471.png)

But tooltip keeps working, correctly showing content in it. So in other words, it just prints this error on mouse move, but printing this error to the console `does not break` anything. 

To suppress this error printing I set `pointer-events: none;` to remove any cursor events. 

I debug the error, but could not find what's wrong. It is a vega-view error and happens at this [line](https://github.com/vega/vega/blob/1f14aa2acfa34825e3809a7076553504b0ef90db/packages/vega-view/src/events-extend.js#L51).

So I am just removing `pointer-events: none;` from css styles and let the error be printed!

@sharlagelfand  to enable tooltip, you will need to set `tooltip: true` in `mark` object.

**Comment by sharlagelfand** [comment]
Thanks @giorgi-ghviniashvili! 

Some initial thoughts on this, we probably don't want to display "datamations_x" and "datamations_y" in the tooltips, but rather the actual column names (in the jitter / summarize views), and maybe just the grouping variables in the infogrids? We can control [what's in the tooltip](https://vega.github.io/vega-lite/docs/tooltip.html#channel) and can change the title of variables, or derive a new variable, etc.

Here's what I'm thinking:

Initial infogrid (no groups): no tooltip, or tooltip just saying something like "One point"
Grouped infogrids: Grouping info (e.g. Degree: Masters)
Jitter: Value and grouping info (e.g. Salary: 81.9, Degree: Masters)
Summarized: Value and grouping info (e.g. Mean salary: 90.2, Degree: Masters)

Maybe the grouping info isn't necessary in the jitter / summarized views? But I'll play around and see how it looks.

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand yes, I see that it is possible to customize tooltip and because it is customized in `encoding`, maybe you can include that info in specs and it will just display how you configure. Or do you need me to do some logic on this?

**Comment by sharlagelfand** [comment]
@giorgi-ghviniashvili I think it can be handled on my end! I'm going to test it out

**Comment by sharlagelfand** [comment]
I have a pretty good start on this, here's how things are looking in the group by degree / compute mean salary case:

<img width="1126" alt="Screen Shot 2021-07-20 at 3 41 53 PM" src="https://user-images.githubusercontent.com/15895337/126386079-72a0a89a-56d2-49f2-9fe6-0d9a33fa87c9.png">

So the first frame doesn't have a tooltip (I can add if we think of something!) and the rest do.

I was running into some issues with tooltips on the errorbar. If I look at the frame alone (e.g. as a "pure" vega lite spec, before passed to the JS code), the tooltip shows up (and in the [vega lite editor](https://vega.github.io/editor/#/url/vega-lite/N4IgFgpglg5mAuIBcBmADGgNCA7lAJvGMuliACQDOAxpALYCGy488ADpUgPRcBuEMBgDoYUIgFcARkKgB7LjXoM+AhgFoANmIh8ArEIBWlWQDsQ2OhHhMkoBgA8IlZADMGGyhGz4n1AE5QbPByZkggAAoasvAABJYMJjEAyu4MfgCeMbIuMRAMtDEwfrLibJgxeES5fsV+kmkgAL7eDNbIoLzu4k7IANqgMBB0UCZQAPoEyACM2AAiAn4QEMwAsgyU8BB+zi3WjMGmlGP207sM+yFH6cgAnGhCAEwPAGwoKAAsGM9TAOyvZxdDmN0mN4LJZBpgmxbvcnq8Pl9fv8QPhWudWpdgWM-AwcMgABxTIQ3d7vXRoKYofEoZ43XT47AAGVkOC2BJuxKmugeby+72eDwZIAAqmw2GykHchLoUD93ihyWh6fibjdmgMhiNxpMkA85gslqt1pttuYUWjASYjickDNzXsMUDrpLYS83p80N8-igAY6rViwRCoTDHm6EZ6kT77eiDv6QTi8Uh8Q8hCqZRhdM93smpkLmay-OzOdzeZ7+YLsKLxYWXdLZfLFcrVeqQINhqMJvgSPqioawmsNlsdtHLdbTiO-VcQ3D3Yjvb7Y1dQeDIYFp2GPV7kaiHYusQmCShHs9M78Hu8fg8lXqQPmJSrizzSFmBUKqxKpTK5QqM-iVWrMA1dttS7JB3h7RZln7Y0hzNHcY0xG07Xg0dgXXeFN0jBdMRBQNV2hWsZ3DLcoxQyd91xAkU3-XQLxeE93jtO8awfG4uSfPlX0rMUP3uL8G1-f8WzbLVO2QXQIL7EABxNYcyL3JDsKddDZwjecJz3XCV2DQiNznbcLXI+NKNrXMfh+NjKWeCyphuJkWXvDk2JLZ9yzfHia0-esfyVP9m0A1tNQ7HVnkkqDpJg00lP9RSNJwlTiKwuKnWXIM110jD9NIwzNOxEypRQSkVTQN5ZRlJiHJYpz2NLF8KxFDyQ34nymwAoDRJ1H4wqNQcouSmLx3k+KMtUkjoqXPCdKlIjMPUoaUoPWs3hPH5dF0OUSQpeyCyLZyOLLLiGurJrvMbPy2sC4CxKTbroN6uScsQwbHuUkbErml641S-CEtmgzdxwvLEwfZ4-10LkfmTBVkWY3aatcw7308vjTsE-z2uC0C7JAeZe3CmTYPG45noB17pr0tT-oQlLJvS8nMsp7LSa+xaQfWlA2JJWUaW2xzH1qtzuOO2tmrOoSApEzHpjIXHIJ62S4M+sdbSJ516dGpL5q+2mCPV96qdQ4zgY5QkStzUk5SmZ5QtvSq4Zczj6qRk7vzF9HLo60CpjtWWpIJvqteV5ClbQt6-qZ6nte0unXQZsb+qXRapSmUk1qVSkKSVXmqv5hGncakXUd88WMZA6Yb19-HIoe5mg9V36stV76ptjjWPtrijE2m3Qbh+DAHhuB5LxT7P7f2ur3OFrzXbRi7JbL20o0r+XCYT4mVbXtXW-1iPDebmPQzjzWQ6Not6TQS8-lJM3sdhpNqodg786nlGZ+L935+ukecYNKv7sVjusVA6hz1uHJuOsG6MybknIkF5Vq0loq8X4XVbY7XvrnR2k9eJ1jfq1YSQUF5cluhFf+RMgEn0gfHYBWk0q623mAzeQMmrvAeCnDASoBSsNHugvaAtEYF2ngJd+c8CFfxtsvO6CsyEk0jlOMOjdGEQPkVAxhSd7h0jQMmdMtl0BRjvqxeGmChbYNFrPfBV0dS-GIf7Gusj17Bw7lvQ+bcDZGX3nQ5xO9oEmXxO8IQKAHinkvvSVUei7Y8MMU-LByMcFCLwRLURlihQSJIVIte5DHGUOPo49xWT252NPrWP4mini+PButG8+iH7j0FkdExRd4mly-tjFJNiAF2IyQUvJrjcpKNAQo6hTDJRElYe8OkYMTz4k0dwgxj8J7GJiaY4R5jPbICvNY6u7TUKdMNt03ebi+n0IGSfIZbEhDZm9mtVU+IZSDxmdUvhz96m4POisqWuofa-xXgHEOOyjJ7PAdHDxM1jk5JgY8Eq5J6Q-G9rZe5GCokLJdnE15CSLGgSeBs0h6SZG7OUVQk5hzPEMMGazPxbDQaFUCTyFU8LeF52icilqqKmk6h5FitJwC-maQBYooFvLSX5XUew1U-JzJwtQXzelRi6mLIaSyj27zzwctXly3F-z8XZIKbkzV+S97go+BebkFJvZPEqeE2ZNT+Ev1icykuiqF6BJVT8wB6qeW6p6YDIlIKVGCq7vcb4tJzwCg+DcQqdLInzNlUyt2Ij0VrPEV8yRqrfluuGv031hL+Uev2blcFvwbg3LeFMc8VJwKSpztKxF0bC4vPtZ-NlKDWmbOkRvahAqs20I7WC-KIyxn1lBjyK2NsqkIqjc7WtKL62JIxckpNqSU2urbRQnNgKu2rtUb285aB+2yj7mDFBo6q3joEa-KdH8Z1rJafOtpraHFdI3YM71FMCU9q7kSb2J4FQfD-MgiNczakTsEXai98bUAyxvS2nFy7MmPs7T9ODb7bgfs9PiLMA8w2DzCWgy1jzGWTpA3G1ZqBPl42+bY7ZaayZHMzTk59R89VuLUUIayO7BQlWsiWiqOGHkMqRQR2NbyF4BOdRR8i3L000dfdq+jLjc2A3BfyQt-JOMW3NTxsdgHT22sE2i4jbxRNbPE1RuM3aZPZozdJ-VW6lQWQ4VbPupJ-1WqeXKutoH9PlubditVMGH2Wa1XvWTXjN3+uJPKUkVsB74lWhJCtY88P8eA7p1loEFSGbvfXRD5n10BcY3mrdvxPhrT7kPcpznEs1uS2YvT7yeY-zI8ml1HSTNyLy56mmFmpOBaY1u88FJuQ8i-aqCrfGqtnsI0J66soMvQfvXi9r8nOu5e6-lhTQrpQmqpNSQUNy8wWt4zKoDE2UsOum3OxrC7muUb8wt1bHWo4reJaC7VrN9C8gCRSUNbF9saePVpm1SzGlnZ1BzWbvn5sasW2uhD0PQshmeDutAA8PiBICepqVkaAfPPPUR95nxweptu1D+7S3Huw9J944G+gxng0YtSNAoTfuY4A9anHk3asL0YoTpdkP3Vw6fV157tHXtbo9OSJT551ojoO5ptnbncdTZ1CwnnLXif88p3yp7PqrO9ffUIFOfxVQ3ER73cN8WIms9czGmrqXkDylVzdvnknhe696ULnXPWCthcc9Cv8rDwbM8rVj+XNvlmc+uk5hrcsmtiYUq1kBmvBfa5fV79bYXvh-llLZXxq1y1HpD9bgTtuQegTJI74z6uXee7W8tinru08LQ25mN44MSroDhKNo72mgcKobWXxNl3b1zaywL+DLcG+15Zs3wttlaIKhhVwi3uGxvHZ0yX-v9um2QZ80T531HJ8PYmh71PU-E6Fb7iVT4LxL7cZZy5-D1Xw927AhdmPV249PSrwfmvR+Awn4Yz-0KSlDlEvBizpG5kJC72rTX172nTAzGQr3j2-1M2yyCwALkyp1uBTApG+ENxuUzD-GgJPUB3lXgOI3JCQK-331QLHzowwJCz9WwMeEJC5i-FCXz1l3+1D2L2f1L3ElI3f2Hwh1HyT3HwPl-zJ3P312NS5FzB5E9E9GIOxwVw5xf25CoKBAkx-1PyAJ1ToNFy7hTH6xDXojuFzGUJ4Kf2B03yQBlE0IGhQLazEPoJT0AKkM7gJD8Vok0RlCzBNymAvksKL2sL70vTsK8x305T31EMPw8JoXr0kKwOGRYythTipX5HlEPS4ML0fxOw33CLWgcLrk3jM3QLcMwPh0lBwMYiU3rHlBi2CLyPXz4NsMzGKPsViKSK10SN0PiNOWMMHhTkLVQ0RyDwS1Xx7zII83eXWg6O0NoJcJy16PcOSLOVpEJHBieELSmXGMtwfyS3yNaMKLfz9igxENKLQIOQYJJROXBRVERwvH8KvGtiaMOJaJsMKOvSH3OJiMuIMPKJWMqKYOqPOTMmHmth7kQOX0OxgKmPczxwXkR3mITycW6OTyBMYLuK3Ri2th+EKkhh3SIJhLlxCKOM+LA2+BRKcMTziJhwn3ROxKMP8SmXlECU+EhhmxJO4LJI+LCMpIriiMXTVxoOcLpJ6IZL6LWJTDPBN1WkHnZOw3v0q1gOmMROumRG82iN5y6KlIlIkL1JBMHgN0G2TF21VBPDePGz5PIPeSzGpNFNpMZNcMxNuKQyTBp2+HPBJBVCmQHitNVIRKV1AktOjzON3x1P+KWMBMlNWKqONNsjJEzEZwvgvFvhyKt2aLgJmKRMHyEN+MjPbSuPdwqKxPdLOSuRhQeJeJKgDPhMVwjxCm3x+IjJFN1LjIxNjOBKZOQ2JAVJLR7kFDmO5NyPeOzPVJClOL-m1LbKjPFM7INI7J7NBP5BuUYgHnPHxOyL+1HOtPHODOQFpAdPbO7JdK7LLMMN7MLUHlVECUHWRzrNIKDMbNAj7mPLnOdOWPPLdMvJSNVBbyeICVBj2JX27yfIbJfxhXfKLIBOuNLJ-Os2ZPQF8RuVpCU3sJHMzLHLVIPKQEvGgpXVgpLNdJe0Qt7NdhhShKhgx2Dywr3JwpfOQHxOIXCDAFmCM2QJvCLL-EeDJERy9NeFYWxgXIIh4ql34pLUEolRBN8XOTQ2pFbyGyHhmR+GlAHlAItLGQlQnR4oCMyLvPYlwrlBYrYo4q-y4pXTEr4ojDdCEvpPSisuTIEoCWkuXOpFTCU0pB2MlxUrUt7jTJNy0uxh0vxGJG+H0tPG5CMrixSVYvYtbQstg0coktstcrPIctCvEpsqkuErcqPFWkKipADzlGsl8u5H8oskCs5n410vCvQ0ioeCMrzKkjirMq0LWSy2SuypctyvStEsyusucrsqqJuWPB21JCpSzBAtUvKo0qqu0oLlqpTnqu+CisYrwubPf1aoSs6oGqcskp6vsv6t4v2tSt6t-LOWK1YVzFhTQ23PvBmvUoCv8IWuFiWoitWsavWshhMviug0SofS6qGrSq-IypOpSpyuSNGt5DYivhN1pBlxw0eoqs0uqprXepWsMu+u+K2tMp2suKBoOuGpEoJD2ohsOvjJTB-U2imQ+BpERoer8rmpeuCsWtCr0sxrWpfymV+rascIBrxUJrOqOtJvBu6uJrcr8XxN8SzEqqeOmqZueqCpqvZrqpYQatwqgLDPCm2v+t2rFuBvOpjLBqysNqhv0C+AIKeBKhNTKqesqpZpVrCuWvVs+s1sFMu11t8wFo1SFshv1OOtNqJpBrIo9IN1eC+FBkLRPDvxYmRuZuVvRtVpdoMq5v4KTCXnnS9qJx9vdT9oppJqTDJvFpDr1wJHe3Mmz34v8IVtmqVrRpCudo+qxu5siM9rxr1oJuLrNoDtFqDuFpGotuTD-DJECPBg+DtpRvmtZreuTubrTtsJuV5vxu4u7uDqNrgoQ3zolvdLQyECVCpFuUCU0QvEnoTobrZqbs5q+u5uap1o7u9v1v7v9sLu3tLu91uCPCtmRwFCtkYhJFjoJHjvrtevvDnuvs1s2paofpzqfsGvXpFqLoNoQcHs5DLB7kHlp0AaTGAYdsTsbo5tdpbvTuJNipgaXVzuGjfo3uIp0mobWKPE+ELTWnJEFDuE4KRsVrwYvtnqvqIYXvCNpW1uYGzoobgdOpfvEMDvgYHpkueH3s+HhHKTJGzDPpAZnrAb4dTpvvTruGXs7tXuQdkakb7pkckfLKPFs09CHhKizyVLjq4dRtAZYnAf4Z0dsLYn0cfq7qMfMdBukYkYLrcvkdJDomTEZ1+G-n0VwacY0Zca0Y1vWruWEbCFEbV0odenod7qQefqCfLJTHxKKp3TDQskaOXxienqdsIe0dwrDS8dgZ8dyZ3v8dMcCeadDr3ppEhj-FKwvl7jUe4ecdFuqcSZfxJHqbEcabMbyZaZyemfabLpwYUbuAHhLTQxeAGdiaqbVpqaSZiqzvIfSfEfJoWdoZNvmffvT0-vDowDYlpCtihU2cqaToSbdqSbvpEcOZuwydQKydfrXuMd3vkcHRhQVHlDLHTM4brsGbieGZ2dGd0agfvr+u8cMaacubrzoYBb8dDrDSED7nQAwcPqvyecdpeZGbebGanM+ZRYabRYuZoa9WzT+bctUvlFhpJDlECXBlJfwcvopeIY8ZxugdpcmfpbaYxfJyxd8ZmdxaPAUvMieCiydXKcceeYIfhcpfTsCIg3btFaOamYlcZcxfOaNbWL8WRzkIHOth9N5Z4c0YFaioAF1mgQANAGB0gJR+gQBGA-AABrZgLYWoeoQsbACAEwagWQfAEYGAdoEAG0UAFwKACADQUCHFbAeAdIcUZgAAR3EASGCGsGCH4DNAcCgGcFsBAE6A0G6Ard6BmAeCdewHdckBTYAFF7A2AawQBihxATB8AAAKHccQOgIQFtlNgAShiAAF5p2YgpgYgAB+GIAAchsRXZiCQFXbipXbNHHY0AAEETAYANAoI1A7hXXC3T3mBl5sAaB3AoJQB8BZBGARg+g+JMAUxdAXXXXnRE3k3U3mAmCM2s3wo82C2xAMQS2M2xBr2wh4gTAB2Uh3WMgJ2zR724On2X2GA32kBehCRwsyQvtqQEEGQSR96A9TVMw0L8Qf2M3s1vWk2U202SaQPs2whwOTBC2oPlgYP4A4OfW8hEPkO0h0g0OWwmPAOwhnY2PwoTAX2Rh3AzQr3woEOkPUhUOYgABqGIDYBIVEPwfAaoWoJoAKSTtN2GWT5geT9sJTvjgTtTkTzTtQXT6wfttIIzoN2QQsCTgDtN29kATN9jkAGzxTjQJoOj0AX1gNytoL8KNgWQEYRAbAJNjQU90CeAPwboV18NyN6N49uNhNkAczoD1NKzjj-NrjyD4t3jkAMtitjoLoHoPDhtptt1hgVtjQDtrt5gXt-tod1oEdsdjrydmdudhd5dtd6uDdrdldndvdkbw949uD89tAS92D8KALjDx9lEbD3D3oD9r9ujkAP94rvz0rzJcrkATj7jmr5Tjb5gRzjTsT9D6gB9uN59190IfDokEkIjoqGkcZTAcjy18Ga1mj47pRRj87sIVjwL0D3Nyr27qAaDwLh7+DoT9TlDl73z5jm9r5K70LkwJTxoH9l1oAA)):

<img width="1094" alt="Screen Shot 2021-07-20 at 3 47 08 PM" src="https://user-images.githubusercontent.com/15895337/126386471-20e95b92-fcb6-4a2c-993b-8cf04c744a02.png">

But it doesn't show up once passed through the JS code - @giorgi-ghviniashvili are the errorbars "hacked" too, which might explain why the tooltip doesn't work for them? [Here](https://github.com/microsoft/datamations/blob/tooltip/sandbox/errorbar_tooltip/errorbar_missing_on_tooltip.json) are some example specs.

Maybe showing a tooltip on the errorbar is overkill and we don't need to worry about this anyways - @jhofman thoughts?

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand that's because there are two `div` stacked and top div for main viz has priority in terms of pointer events and only first div's events are captured. Background `div` pointer-events is enabled but not captured because top one covers it. 

If we delete top layer, then it is working: 
![image](https://user-images.githubusercontent.com/6615532/126477887-d169d60e-27ad-40fe-8f33-6503b4b558fb.png)

That's downside of hacking things, I can't make this work.

**Comment by sharlagelfand** [comment]
Thanks for clarifying @giorgi-ghviniashvili!
