### ISSUE TITLE
Use slider to change tab in Shiny app

### ISSUE THREAD

**Issue by sharlagelfand** [microsoft/datamations#56]
As a next step on #30, looking into if it's possible / how difficult it is to have changing the slider in the datamation update which tab of data is shown in the app.

**Comment by jhofman** [comment]
just catching this now. it's a great start! a thought: maybe for limitation 2 below we could always go to the "beginning" of a given group-by step?

not sure how to solve limitation 1, seems like it requires some javascript magic. maybe @giorgi-ghviniashvili has some cool hacks?

**Comment by sharlagelfand** [comment]
The [latest version](https://sharlagelfand.shinyapps.io/datamations/) of the app has it so that changing the tabs changes the frame of the animation (to the "beginning" of the group by step, as you suggested @jhofman - thanks!). It's a bit buggy so I'm refining it still - and will continue poking around to see how we might get it working the first time the animation is played through.

**Comment by sharlagelfand** [comment]
I've implemented it so that the slider updates the tabs, the tabs update the slider, _and_ when the animation actually plays through for the first time / replays, the tabs are also updated. Updated app is [here](https://sharlagelfand.shinyapps.io/datamations/).

@giorgi-ghviniashvili the PR #70 adds to the JS the code to have the animation "play" / "replay" send the slider state to Shiny as well so that I can use it to update the tabs

**Comment by sharlagelfand** [comment]
Closed fully by #76.
