### ISSUE TITLE
Possible to have dynamic width of slider bar / description?

### ISSUE THREAD

**Issue by sharlagelfand** [microsoft/datamations#57]
Curious if it's possible to have the width of the slider bar and description adjust to the width of the actual plot (which isn't fixed):

e.g. instead of spanning the whole container

<img width="632" alt="Screen Shot 2021-05-25 at 10 41 49 AM" src="https://user-images.githubusercontent.com/15895337/119518014-20c3df00-bd46-11eb-8590-58162194c2c5.png">
<img width="997" alt="Screen Shot 2021-05-25 at 10 43 25 AM" src="https://user-images.githubusercontent.com/15895337/119518020-228da280-bd46-11eb-890c-9a66d927c038.png">

only being as wide as the final plot is? @giorgi-ghviniashvili is this possible?

<img width="626" alt="Screen Shot 2021-05-25 at 10 42 08 AM" src="https://user-images.githubusercontent.com/15895337/119518058-2c170a80-bd46-11eb-8f17-2eaae780ced2.png">

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand  yes it is possible, we need to set same pixels width to `div.control-bar` and `description` as chart's.

**Comment by giorgi-ghviniashvili** [comment]
Implemented it:

https://user-images.githubusercontent.com/6615532/119670888-56ea8700-be4a-11eb-8766-cd826ab42742.mov

**Comment by sharlagelfand** [comment]
Thanks, this looks great!!

**Comment by sharlagelfand** [comment]
This is in the latest version of the [app](https://sharlagelfand.shinyapps.io/datamations/), so closing this now!
