### ISSUE TITLE
Angle x-axis labels so they're not cut off

### ISSUE THREAD

**Issue by sharlagelfand** [microsoft/datamations#58]
Discussed already with @giorgi-ghviniashvili, but right now long x-axis labels are cut off (Dream isn't shown at all)

<img width="518" alt="Screen Shot 2021-05-25 at 10 46 02 AM" src="https://user-images.githubusercontent.com/15895337/119518334-6c768880-bd46-11eb-839a-0f6a484d4d99.png">

We should either: pass the angle for the axis labels in the specs, or set them within JS to all have labelAngle = -90, so it looks more like this:

<img width="635" alt="Screen Shot 2021-05-25 at 10 49 21 AM" src="https://user-images.githubusercontent.com/15895337/119518877-edce1b00-bd46-11eb-83d7-16a0ed6b5082.png">

I'm inclined to just have this handled on the JS side and always set them to -90

**Comment by giorgi-ghviniashvili** [comment]
I can set this in axis-layer's spec, but you can also send labelAngle within the spec.

**Comment by giorgi-ghviniashvili** [comment]
Ok @sharlagelfand , done it: 
![image](https://user-images.githubusercontent.com/6615532/119709356-2c122a00-be6e-11eb-8c10-209ea7002511.png)

**Comment by sharlagelfand** [comment]
Thanks @giorgi-ghviniashvili! Which commit has this for me to copy over?

**Comment by sharlagelfand** [comment]
thanks, looks good!
