### ISSUE TITLE
Shiny app can't handle changing data/groups more than once without freezing

### ISSUE THREAD

**Issue by sharlagelfand** [microsoft/datamations#60]
Just to keep track of this so I dig into it... I'm not sure if it's an issue with the way the Shiny app is laid out or how the specs are generated/animated, but will look into it.

**Comment by sharlagelfand** [comment]
@giorgi-ghviniashvili I'm trying to track down why this is happening, in the [app](https://sharlagelfand.shinyapps.io/datamations/) if you hit "Go", then "Go" again, there is this error in the console:

`vlSpec.meta is undefined`

I'm not sure what's making it freeze but could you try it out and look into that error? Thank you!

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand could you plz record a video?

**Comment by sharlagelfand** [comment]
https://user-images.githubusercontent.com/15895337/119733221-340aa380-be47-11eb-9085-63e7f0f39307.mov

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand latest code from error-bars will fix this as well.

**Comment by sharlagelfand** [comment]
thanks @giorgi-ghviniashvili! the latest app is [here](https://sharlagelfand.shinyapps.io/datamations/), the animation plays eventually but the first bit is frozen/choppy and the error persists


https://user-images.githubusercontent.com/15895337/119829117-e8004300-bec8-11eb-9fcd-b8f83676dea1.mov

**Comment by giorgi-ghviniashvili** [comment]
Something is strange here, we need to debug it .

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand ,  I see that init function is called multiple times after click "Go", can you see why it happens? It must only call it once..

**Comment by sharlagelfand** [comment]
@giorgi-ghviniashvili yeah i can see it is called once the first time, then twice the second time "go" is clicked.... I'll see if I can figure out why

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand  if you can't figure it out, I will just use flag variable: `initializing: true | false` and will ignore all subsequent init calls while initializing. Just lmk.

**Comment by sharlagelfand** [comment]
Thanks @giorgi-ghviniashvili - the latest app is [here](https://sharlagelfand.shinyapps.io/datamations/), as far as I can tell on my end init is not being called multiple times but it's still freezing/erroring:


https://user-images.githubusercontent.com/15895337/120211945-6decf880-c1ff-11eb-9ee8-d1da380b3da4.mov

Maybe let's try adding that flag to ignore subsequent `init` calls? Just checking, this will only ignore them "while initializing", but will allow for calling again via pressing "go" / changing settings etc, right?

**Comment by giorgi-ghviniashvili** [comment]
> Just checking, this will only ignore them "while initializing", but will allow for calling again via pressing "go" / changing settings etc, right?

Of course :) It will just ensure that init function will complete.

**Comment by sharlagelfand** [comment]
Ah shoot, different error now when you hit "go" twice on the [updated app](https://sharlagelfand.shinyapps.io/datamations/):

`vegaLiteSpecs[i] is undefined`

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand good catch, please update it.

**Comment by sharlagelfand** [comment]
Thanks @giorgi-ghviniashvili!! It definitely does not freeze now 🎉  Updated [here](https://sharlagelfand.shinyapps.io/datamations/)

It seems like maybe something is "off by 1" in terms of the animation shown - maybe having to do with the initialization?

The first time I click "go" it's the default settings - group by Degree, calculate mean Salary - and this works great. The second time (~18 seconds), I group by Degree _and_ Work, but the animation still shows just grouped by Degree. The third time (~40 seconds), I group by Degree and Work, and calculate _median_ Salary, but the animation shows grouped by Degree and Work, but the mean - so it looks like any time after the first click, it uses the previous iterations specs?


https://user-images.githubusercontent.com/15895337/120237402-2039b580-c22a-11eb-9ba4-c6a81cb8ad45.mov

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand  that's strange. I added console.log statements to print out passed specs. Please update it.

**Comment by sharlagelfand** [comment]
@giorgi-ghviniashvili updated app is [here](https://sharlagelfand.shinyapps.io/datamations/) - the log seems to show the lag in specs from what I can tell!

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand `init` function is called twice after second click on "GO": 

* first with old frames where grouping by Degree
* second call was with Degree + Work (correct frames). 

And because initializing flag, second call (with correct specs) is ignored.  

So this means that there is an issue on Shiny side, it calls init with old specs.. Please check this, it MUST call init only once. 

See video:
https://user-images.githubusercontent.com/6615532/120631993-8e27ec00-c479-11eb-8f3d-550f030eff0c.mov

**Comment by sharlagelfand** [comment]
Ahh super annoying, it should only be calling once... but let me debug further. Thanks for looking into this!

**Comment by sharlagelfand** [comment]
Just to update, I have sorted this out 🙌🏻 🥳 Still working out some fiddly bits for #45 but I'll push an updated version of the app with both features / fixes once that's sorted.

**Comment by sharlagelfand** [comment]
Updated app is [here](https://sharlagelfand.shinyapps.io/datamations/) with this fix! 🤞🏻

**Comment by sharlagelfand** [comment]
This seems all good, finally, so closing now!
