### ISSUE TITLE
Positioning of error bar div is off

### ISSUE THREAD

**Issue by sharlagelfand** [microsoft/datamations#63]
Just keeping track of this separately from the other error bar issues, @giorgi-ghviniashvili looks like the positioning of the error bar div works when the widget is by itself but not when it's in the app (version live [here](https://sharlagelfand.shinyapps.io/datamations/) with it), they don't show up (or are in the wrong place / offscreen?)

<img width="1412" alt="Screen Shot 2021-05-26 at 2 05 02 PM" src="https://user-images.githubusercontent.com/15895337/119710251-2693f000-be2c-11eb-9bf8-13b8a6c24111.png">

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand please update code from `gio/error-bars` branch and also don't forget to copy all the styles from `gio/errorbars ` `index.html`.

**Comment by sharlagelfand** [comment]
@giorgi-ghviniashvili everything is updated, still in the wrong place.

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand , .hidden class is overridden by shiny's utilities styles and it is completely hidden... Will use different class, instead of hidden. For example: vega-hidden-layer.

Please update code from error-bars branch and it will be fixed.

**Comment by sharlagelfand** [comment]
Looks good, thanks!
