### ISSUE TITLE
Cleanup app.js , make comments and easy to read

### ISSUE THREAD

**Issue by giorgi-ghviniashvili** [microsoft/datamations#64]
app.js got very complex and hard to read, let's try to make it simple, clean and easy to read. 

Also @sharlagelfand , have you found out how can we enclose the code in App function, rather than have all props globally available?

**Comment by sharlagelfand** [comment]
@giorgi-ghviniashvili I think we can try this now - the parent div gets the ID so all of the slider, replay, viz, etc are child divs of it, and so the code will be defined in the parent div and hopefully should be able to access the children just fine? I don't know much about the implementation so the easiest way for me to test is to make everything enclosed and then just try it out!

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand , `.hidden` class is overridden by utilities class and it is completely hidden... Will use different class, instead of hidden. 
![image](https://user-images.githubusercontent.com/6615532/119821686-e607a580-bf03-11eb-9e5a-7c6056a07c3e.png)

**Comment by giorgi-ghviniashvili** [comment]
![image](https://user-images.githubusercontent.com/6615532/119822035-4696e280-bf04-11eb-82fe-4c9c5f571fcd.png)

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand  you can take a look at the new code with comments.
