### ISSUE TITLE
Length of initial frame, not shown on replay

### ISSUE THREAD

**Issue by sharlagelfand** [microsoft/datamations#65]
To keep track of, I think the initial frame should be shown longer - it only appears for a split second. And on "replay", the title for it does not appear at all - just goes straight into the group by:

https://user-images.githubusercontent.com/15895337/120004264-8ca38300-bfa4-11eb-9061-675dac26cb56.mov

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand  yes, that's because we show description immediately the animation starts. Maybe I should draw first frame on replay and then have a bit of delay until animation starts?

**Comment by sharlagelfand** [comment]
Yeah, I think it would be helpful to "pause" on each of the frames (especially the first) during the animation, rather than animating immediately from frame to frame

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand  added delay:


https://user-images.githubusercontent.com/6615532/120784003-ae6caf00-c53c-11eb-971c-beb724443683.mov

**Comment by sharlagelfand** [comment]
Thanks @giorgi-ghviniashvili! looks great to me

**Comment by giorgi-ghviniashvili** [comment]
@jhofman did not get it. plz clarify further.

**Comment by giorgi-ghviniashvili** [comment]
@jhofman I think I just fixed that.

**Comment by giorgi-ghviniashvili** [comment]
![image](https://user-images.githubusercontent.com/6615532/121077912-4a224780-c7e9-11eb-97ad-db5f3752ad87.png)
