### ISSUE TITLE
Explore gemini2

### ISSUE THREAD

**Issue by giorgi-ghviniashvili** [microsoft/datamations#69]
yhoonkim updated gemini to gemini2 , which supports keyframe animations - exactly what we need. Let's take a look at [gemini2-editor](https://uwdata.github.io/gemini2-editor/) for some new examples.

**Comment by giorgi-ghviniashvili** [comment]
@jhofman I think the motivation of this extend was to support custom aggregations. Just take a look how awesome it is. 

![0a969b58-cc64-4cd5-9831-8390a8e953e5](https://user-images.githubusercontent.com/6615532/120642070-7c4c4600-c485-11eb-84b0-b9d1849d223f.gif)

**Comment by giorgi-ghviniashvili** [comment]
One thing that I noticed is that, it builds a single animation from keyframes.. Not really what we need, but cool!

**Comment by jhofman** [comment]
wow, that's awesome. i guess we should wait until it's a bit more mature to incorporate, but looking forward to that!
