### ISSUE TITLE
Explore observablehq/plot

### ISSUE THREAD

**Issue by giorgi-ghviniashvili** [microsoft/datamations#74]
I found a cool library called **observablehq/plot**. 

It is an alternative to vega and vega-lite and is very flexible and able to easily integrate cool d3 stuff in it.

I created this [notebook](https://observablehq.com/@giorgi-ghviniashvili/exploring-observable-plot) using it and I am impressed how easy it is to do the jitter. 

Find out more about it following these links:

https://github.com/observablehq/plot
https://observablehq.com/@observablehq/plot
https://observablehq.com/collection/@observablehq/plot

TODOs:

* try animation between plots
* try error-bars
* try custom axis labels

**Comment by jhofman** [comment]
Looks neat but as per [this discussion](https://github.com/observablehq/plot/discussions/434) no super easy way to animate between plots yet.
