### ISSUE TITLE
Authors + maintainer

### ISSUE THREAD

**Issue by sharlagelfand** [microsoft/datamations#79]
Related to #13, administratively we should update the authors (to also include @giorgi-ghviniashvili and I?) since this'll show up on the package website (as will the license, so we should sort that out!). 

We may also want to update the maintainer for the package - this is who people should bother with questions, so not sure if we want to update to you @jhofman? Right now it's still set to Xiaoying.

**Comment by jhofman** [comment]
Good point!

Is there a formal way to update authors via Github, or do you mean listing your names somewhere in a license file or something like that?

**Comment by sharlagelfand** [comment]
Oops I meant to link it in the original issue! For R packages you list authors in the [DESCRIPTION](https://github.com/microsoft/datamations/blob/main/DESCRIPTION#L5) file, and then it populates to the [website](https://microsoft.github.io/datamations/) on the left too

**Comment by jhofman** [comment]
@sharlagelfand will add everyone to the R DESCRIPTION file, change @jhofman to contact author ("cre")
