### ISSUE TITLE
Save output animation to file

### ISSUE THREAD

**Issue by joelostblom** [microsoft/datamations#99]
Thanks for the work on this library, it looks really cool and I am looking forward to incorporating it in my data viz teaching!

I am wondering if there are any options to redirect the output to a file programatically, either `.html` or `.gif` would work great for my purposes.

**Comment by sharlagelfand** [comment]
Just thinking, it would probably be helpful to even be able to export each of the frames individually, so that they can e.g. be laid out all together on a page or gif'd together really slowly, even without considering the animations!

**Comment by giorgi-ghviniashvili** [comment]
@jhofman btw, vega-lite has this details popup which is able to export visualization as png or svg. I hid it because it will not work properly when we hack facets. But it just works when there is `meta: {axes: false}`.

![image](https://user-images.githubusercontent.com/6615532/140475956-12feb99d-68fd-485d-9162-874fb7a40271.png)

**Comment by giorgi-ghviniashvili** [comment]
I made a solution that will just download all frames as pngs. This will also work for hacked facets. 

https://user-images.githubusercontent.com/6615532/140482851-08997a4c-71ef-4cc1-af5e-99f525faa1e3.mov

**Comment by jhofman** [comment]
Note: the gemini editor has an export as GIF button, perhaps we can learn something about how it works?

**Comment by giorgi-ghviniashvili** [comment]
@jhofman managed to export gif using [gifshot](https://github.com/yahoo/gifshot).

https://user-images.githubusercontent.com/6615532/145032703-daeffdd0-0ec4-4181-b858-15982b319781.mov

**Comment by jhofman** [comment]
Is there a way to render and save the GIF within an R script by "hiding" the viewer window or something like that?

**Comment by jhofman** [comment]
this might be trickier than we thought.

@giorgi-ghviniashvili will check if there's a way to generate the gif from a node command line script or equivalent (could require a headless browser, which would be complicated.)

if it's really tricky we put this on the back burner.

**Comment by giorgi-ghviniashvili** [comment]
@jhofman managed to export gif from command line using headless chrome. Thanks to [puppeteer](https://github.com/puppeteer/puppeteer).

From R, we need to first run Shiny app, set the url or even pass url to the node.js script and then run this node.js script that is in the video.

https://user-images.githubusercontent.com/6615532/149141092-484238a4-c5b5-4ed1-8f6e-f1492cbe062a.mov

**Comment by jhofman** [comment]
it's great that this is working.

now we have to decide the interface to exporting a GIF. it relies on having a running page somewhere that puppeteer connects to and runs the `exportGif()` function. this okay but would be nice to streamline.

it seems there are two basic use cases. one where you're in R or Python and want to save what you're doing, and another where you're at the command line, potentially.

thinking about the first use case, it could be that the use runs datamations in R and gets a result in the Viewer window, and then puppeteer connects to that local server to grab the GIF.

let's push this decision off a week or two once we're back into R development.

p.s. also, the GIFs are rendering a bit fast so we need to adjust the number of frames.

**Comment by jhofman** [comment]
@giorgi-ghviniashvili, let's try this: a command line node tool that has the following interface:

* Takes in three arguments: the name of a data file, a (quoted) string of R code, output file name for the gif
* Produces a file on disk with the saved gif

then we can call this from the R side with a `system()` command

**Comment by jhofman** [comment]
@giorgi-ghviniashvili, once the big PR is done, can you see if you can get the "export gif" button into the web version?

**Comment by giorgi-ghviniashvili** [comment]
@jhofman I made this work. PR is not merged yet, and I think I will have this as part of PR as well. 

This animation.gif is exported.

![animation](https://user-images.githubusercontent.com/6615532/158587338-e9019549-4a2e-4243-8d76-51054295e0c2.gif)

**Comment by jhofman** [comment]
done as of #146
